Added poor support for flashing `.bin` firmware files.

diff --git a/util/nodeupgrade/files/nodeupgrade b/util/nodeupgrade/files/nodeupgrade
--- a/util/nodeupgrade/files/nodeupgrade
+++ b/util/nodeupgrade/files/nodeupgrade
@@ -67,6 +67,7 @@ EOF
 include /lib/upgrade
 
 image_type() {
+	# TODO: This should probably be called partition detection, type detection should instead be based on file extensions
 	local base="$(basename "$1")"
 	base=${base%.*}
 	local length=$(( ${#base} - 23 ))
@@ -82,7 +83,9 @@ image_type() {
 		kernel)
 			;;
 		*)
-			base=""
+			# Use file extension  # XXX: Mixing partitions and file types (check code elsewhere for '"bin"' or 'bin)')
+			base="$(basename "$1")"
+			base=${base##*.}
 			;;
 	esac
 	type=$base
@@ -128,7 +131,13 @@ remote_file_hostname() {
 }
 
 check_partitions() {
-	if [[ "$IMAGES_COUNT" -eq 1 ]]; then
+	# TODO: Partitions should be part of file names
+	if [[ "$IMAGES_COUNT" -eq 1 && "$type" == "bin" ]]; then  # TODO: Should probably be done differently
+		if ! grep -q -E '"firmware"$' /proc/mtd 2>/dev/null; then
+			echo "Missing required partition(s)."
+			exit 1
+		fi
+	elif [[ "$IMAGES_COUNT" -eq 1 ]]; then
 		if ! grep -q -E '"linux"$' /proc/mtd 2>/dev/null; then
 			echo "Missing required partition(s)."
 			exit 1
@@ -237,6 +246,9 @@ check_image() {
 			;;
 		kernel)
 			check_lzma "$image" || return 1
+			;;
+		bin)
+			check_bin "$image" || return 1
 			;;
 		*)
 			check_trx "$image" || return 1
@@ -400,12 +412,15 @@ for image in $IMAGES; do
 	# We first check for image type as this also checks for image filename length
 	image_type "$image"
 	if [[ "$IMAGES_COUNT" -eq 1 ]]; then
-		if [[ -n "$type" ]]; then
-			echo "Invalid image type or missing image filename argument."
-			exit 1
-		fi
-
-		FLASH_IMAGE="$image"
+		case "$type" in
+			bin)
+				FLASH_IMAGE="$image"
+				;;
+			*)  # "root" or "kernel"
+				echo "Invalid image type or missing image filename argument."
+				exit 1
+				;;
+		esac
 	elif [[ -n "$ROOT_IMAGE" ]]; then
 		case "$type" in
 			root)
